language: python
python:
  - "3.6"
  - "3.7-dev" # 3.7 development branch
script:
  - pip install nose2
  - pip install urllib3[secure]
  - pip install prospector[with_everything]
  - nose2 -c setup.cfg
branches:
  only:
  - master
