# staging would be better for the overview but is to damn hard with travis

language: python
os: linux
dist: bionic

python:
  - 3.7
  - 3.8

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

install:
  - pip install --upgrade -e .[dev]
  - unidown --version
  - cd test-plugin
  - pip install --upgrade -e .
  - cd ..
  - pip install codecov

script:
  - python setup.py clean --all
  - python setup.py bdist_wheel
  - flake8 ./unidown
  - pylint --rcfile=setup.cfg ./unidown/ || true
  - pyroma .
  - pytest -v --cov-config=.coveragerc --cov=unidown --cov-report=xml --cov-report html
  - python setup.py check -v -m -s
  - twine check dist/*
  - sphinx-build -b html -j auto -T -E -a ./doc/ ./build/doc/html/
  - sphinx-build -b linkcheck ./doc/ ./build/doc/linkcheck/

after_success:
  - codecov
  - java -jar codacy-coverage-reporter-assembly.jar report -l Python -r coverage.xml

deploy:
  - provider: script
    script: twine upload -u $PYPI_USER -p $PYPI_PASSWORD --skip-existing dist/*
    on:
      branch: master
      repo: IceflowRE/unidown
      tags: true
