language: python

matrix:
  include:
  -
    if: tag IS blank
    python: "3.6"
    env: PY_VERSION=py36
  -
    if: tag IS blank
    python: "3.7-dev" # 3.7 development branch
    env: PY_VERSION=py37

addons:
  apt:
    update: true

install:
  - pip install --upgrade -e .[dev]
  - pip install codacy-coverage codecov

script:
  - ./scripts/build.sh "$PY_VERSION"
  - nose2 -c setup.cfg -v

after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -v -r coverage.xml

deploy:
  - provider: script
    skip_cleanup: true
    script: twine upload -u iceflower -p $TEST_PYPI_PASSWORD --skip-existing -c $TRAVIS_COMMIT --repository-url https://test.pypi.org/legacy/ dist/*
    on:
      repo: IceflowRE/Universal-Downloader
      branch:
        - master
#  - provider: script
#    skip_cleanup: true
#    script: twine upload -u iceflower -p $PYPI_PASSWORD dist/*
#    on:
#      repo: IceflowRE/Universal-Downloader
#?      tags: true
#      branch:
#        - release
